apiVersion: batch/v1
kind: Job
metadata:
  name: iopl-test
spec:
  template:
    spec:
      containers:
      - name: iopl-test
        image: quay.io/robbmanes/iopl-test:latest
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - SYS_RAWIO
      restartPolicy: Never
  backoffLimit: 2

